dataset:
  config_file: dataset/kitti3dobj.yaml
  dataset_class: Kitti3dObjectDataset
logging:
  ckpt_eph_interval: 2
  path: ''
  suffix: ''
model:
  config_file: model/simulator_model/vae_gan.yaml
  model_class: VAEGANModel
training:
  device: 'cuda:0'
  epoch: 100
  optimizer:
  - name: encoder_opt
    paras:
      betas:
      - 0.5
      - 0.999
      lr: 0.0001
    type: Adam
  - name: discriminator_opt
    paras:
      betas:
      - 0.5
      - 0.999
      lr: 0.0001
    type: Adam
  trainer_class: VAEGANTrainer
  tensorboard_out_path: default
